plugins:
  enable_ebay_ads:
    default: false
    client: true
    
  ebay_epn_id:
    default: "5338988822"
    client: true
    
  client_id:
    default: ""
    client: false

  client_secret:
    default: ""
    client: false

  ebay_topic_id:
    default: ""

  ebay_seller_allowed_groups:
    default: "3" # auto group staff
    type: group_list